swagger: "2.0"
info:
  title: Auth Api
  description: Auth API
  version: 1
consumes:
  - application/json
produces:
  - application/json
paths:
  /:
    get:
      summary: hello world
      tags:
        - default
      parameters:
      responses:
        "200":
          description: Success